### PR TITLE
Initialize Project with ANT

### PR DESCRIPTION
**Pull request by darksky6666**
A PR to initialize the project and setup auto code testing 😉

### CODE REVIEW

**Comment by Linusbeh** [comment]
thank you Sky  😉



Best Regards,
Dark Chocolate

**Comment by Linusbeh** [comment]
You damm pro using Github ><

**Comment by darksky6666** [comment]
You are welcome 😎

**Comment by darksky6666** [comment]
You can do this too hahaha 
Actually it's quite easy if u installed GitHub desktop 😉

**Pull request merged**
